dist: trusty


sudo: required
services:
  - docker


script:
  - .travis.d/build.sh

env:
  global:
    - HACKGPROJECT_REV="7fe8037657ee0faa6bc717fb367a28333e5ffee5"

    - DOCKER_ID_USER="HackGT"


branches:
  only:
    - gh-pages
    - /.*/
