dist: trusty


sudo: required
services:
  - docker


script:
  - .travis.d/build.sh

env:
  global:
    - HACKGPROJECT_REV="63e076ceb3722328c9e7937779aab7c0935ed04e"

    - DOCKER_ID_USER="hackgt"


branches:
  only:
    - gh-pages
    - /.*/
